export const GET_ORDER: "GET_ORDER" = "GET_ORDER";
export const GET_ORDER_STATUS_LOADING: "GET_ORDER_STATUS_LOADING" = "GET_ORDER_STATUS_LOADING";
export const GET_ORDER_STATUS_LOADED: "GET_ORDER_STATUS_LOADED" = "GET_ORDER_STATUS_LOADED";
export const GET_ORDER_STATUS_FALSE: "GET_ORDER_STATUS_FALSE" = "GET_ORDER_STATUS_FALSE";
